<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260905105033 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, currency VARCHAR(3) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(30) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81398E09979B1AD6 ON customer (company_id)');
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(20) NOT NULL, amount NUMERIC(12, 2) NOT NULL, description VARCHAR(255) DEFAULT NULL, expense_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6979B1AD6 ON expense (company_id)');
        $this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount NUMERIC(12, 2) NOT NULL, method VARCHAR(20) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, sale_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D28840D979B1AD6 ON payment (company_id)');
        $this->addSql('CREATE INDEX IDX_6D28840D4A7E4868 ON payment (sale_id)');
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, unit_price NUMERIC(12, 2) NOT NULL, stock_quantity INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D34A04AD979B1AD6 ON product (company_id)');
        $this->addSql('CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sale_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payment_method VARCHAR(20) NOT NULL, discount NUMERIC(12, 2) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, customer_id INT DEFAULT NULL, seller_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E54BC005979B1AD6 ON sale (company_id)');
        $this->addSql('CREATE INDEX IDX_E54BC0059395C3F3 ON sale (customer_id)');
        $this->addSql('CREATE INDEX IDX_E54BC0058DE820D9 ON sale (seller_id)');
        $this->addSql('CREATE TABLE sale_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, company_id INT NOT NULL, sale_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A35551FB979B1AD6 ON sale_item (company_id)');
        $this->addSql('CREATE INDEX IDX_A35551FB4A7E4868 ON sale_item (sale_id)');
        $this->addSql('CREATE INDEX IDX_A35551FB4584665A ON sale_item (product_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649979B1AD6 ON "user" (company_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_email ON "user" (email)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D4A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC005979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0059395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale ADD CONSTRAINT FK_E54BC0058DE820D9 FOREIGN KEY (seller_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_item ADD CONSTRAINT FK_A35551FB979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_item ADD CONSTRAINT FK_A35551FB4A7E4868 FOREIGN KEY (sale_id) REFERENCES sale (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sale_item ADD CONSTRAINT FK_A35551FB4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09979B1AD6');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6979B1AD6');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D979B1AD6');
        $this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D4A7E4868');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD979B1AD6');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC005979B1AD6');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0059395C3F3');
        $this->addSql('ALTER TABLE sale DROP CONSTRAINT FK_E54BC0058DE820D9');
        $this->addSql('ALTER TABLE sale_item DROP CONSTRAINT FK_A35551FB979B1AD6');
        $this->addSql('ALTER TABLE sale_item DROP CONSTRAINT FK_A35551FB4A7E4868');
        $this->addSql('ALTER TABLE sale_item DROP CONSTRAINT FK_A35551FB4584665A');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649979B1AD6');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE payment');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE sale_item');
        $this->addSql('DROP TABLE "user"');
    }
}
